<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SpiritVale.Overlay.Api\SpiritVale.Overlay.Api.csproj" />
    <ProjectReference Include="..\SpiritVale.Overlay.Capture\SpiritVale.Overlay.Capture.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\skill-catalog.json" LogicalName="SpiritVale.Overlay.Domain.Resources.skill-catalog.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
