<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpiritVale.Overlay.Api\SpiritVale.Overlay.Api.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
